package com.peersolve.model;
import java.time.Instant;
import java.util.List;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
@Document("problems") public class Problem {
 @Id private String id; private String title; private String description; private Difficulty difficulty; private List<String> topics; private List<ProblemExample> examples; private List<String> constraints; private String starterCode; private List<TestCase> testCases; private String expectedTimeComplexity; private String expectedSpaceComplexity; private Instant createdAt;
 public String getId(){return id;} public void setId(String id){this.id=id;} public String getTitle(){return title;} public void setTitle(String title){this.title=title;} public String getDescription(){return description;} public void setDescription(String description){this.description=description;} public Difficulty getDifficulty(){return difficulty;} public void setDifficulty(Difficulty difficulty){this.difficulty=difficulty;} public List<String> getTopics(){return topics;} public void setTopics(List<String> topics){this.topics=topics;} public List<ProblemExample> getExamples(){return examples;} public void setExamples(List<ProblemExample> examples){this.examples=examples;} public List<String> getConstraints(){return constraints;} public void setConstraints(List<String> constraints){this.constraints=constraints;} public String getStarterCode(){return starterCode;} public void setStarterCode(String starterCode){this.starterCode=starterCode;} public List<TestCase> getTestCases(){return testCases;} public void setTestCases(List<TestCase> testCases){this.testCases=testCases;} public String getExpectedTimeComplexity(){return expectedTimeComplexity;} public void setExpectedTimeComplexity(String v){this.expectedTimeComplexity=v;} public String getExpectedSpaceComplexity(){return expectedSpaceComplexity;} public void setExpectedSpaceComplexity(String v){this.expectedSpaceComplexity=v;} public Instant getCreatedAt(){return createdAt;} public void setCreatedAt(Instant v){this.createdAt=v;}
}
