"use client";
import { useForm, type Resolver } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import Link from "next/link";
import { useRouter } from "next/navigation";
import api,{apiError} from "@/lib/api";
import {auth} from "@/lib/auth";
const loginSchema=z.object({email:z.string().email("Enter a valid email"),password:z.string().min(1,"Password is required")});
const registerSchema=loginSchema.extend({name:z.string().min(2,"Name must be at least 2 characters").max(80),password:z.string().min(8,"Password must be at least 8 characters"),confirmPassword:z.string()}).refine(d=>d.password===d.confirmPassword,{message:"Passwords do not match",path:["confirmPassword"]});
type Values={email:string;password:string;name?:string;confirmPassword?:string};
export function AuthForm({mode}:{mode:"login"|"register"}) { const router=useRouter(); const schema=mode==="login"?loginSchema:registerSchema; const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<Values>({resolver:zodResolver(schema) as Resolver<Values>,defaultValues:{email:"",password:"",...(mode==="register"?{name:"",confirmPassword:""}:{})}}); const submit=async(v:Values)=>{try { if(mode==="register"){await api.post("/api/auth/register",v); router.push("/login?registered=1");} else {const {data}=await api.post("/api/auth/login",v); auth.set(data); router.push("/dashboard");}}catch(e){alert(apiError(e));}}; const label=mode==="login"?"Welcome back":"Create your account"; return <main className="grid min-h-screen place-items-center px-5"><section className="card w-full max-w-md p-8"><Link href="/" className="text-xl font-bold">Peer<span className="text-cyan-400">Solve</span></Link><h1 className="mt-8 text-2xl font-bold">{label}</h1><p className="mt-2 text-sm text-slate-400">{mode==="login"?"Log in to continue learning.":"Start learning with your peers."}</p><form onSubmit={handleSubmit(submit)} className="mt-7 space-y-4">{mode==="register"&&<Field label="Name" error={errors.name?.message}><input {...register("name")} autoComplete="name" /></Field>}<Field label="Email" error={errors.email?.message}><input {...register("email")} type="email" autoComplete="email" /></Field><Field label="Password" error={errors.password?.message}><input {...register("password")} type="password" autoComplete={mode==="login"?"current-password":"new-password"}/></Field>{mode==="register"&&<Field label="Confirm Password" error={errors.confirmPassword?.message}><input {...register("confirmPassword")} type="password" autoComplete="new-password"/></Field>}<button disabled={isSubmitting} className="btn-primary w-full disabled:opacity-60">{isSubmitting?"Please wait…":mode==="login"?"Login":"Create account"}</button></form><p className="mt-6 text-center text-sm text-slate-400">{mode==="login"?<>New here? <Link className="text-cyan-400" href="/register">Create an account</Link></>:<>Already have an account? <Link className="text-cyan-400" href="/login">Login</Link></>}</p></section></main>; }
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}) { return <label className="block text-sm font-medium">{label}{children}{error&&<span className="mt-1 block text-xs text-rose-400">{error}</span>}</label>; }
