
spring.config.import=optional:file:../.env[.properties]
spring.application.name=peersolve-api
spring.data.mongodb.uri=${MONGODB_URI}
server.port=8080
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION:86400000}
app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://localhost:3000}
app.judge0.url=${JUDGE0_URL:}
app.judge0.api-key=${JUDGE0_API_KEY:}
app.judge0.api-host=${JUDGE0_API_HOST:}
