"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import api,{apiError} from "@/lib/api";
import type {Problem} from "@/types/problems";
import {Badge,format} from "@/components/problem-ui";
const difficulties=["ALL","EASY","MEDIUM","HARD"] as const;
export default function ProblemsPage(){const [problems,setProblems]=useState<Problem[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState(""),[difficulty,setDifficulty]=useState<typeof difficulties[number]>("ALL"),[topic,setTopic]=useState("ALL");useEffect(()=>{setLoading(true);api.get<Problem[]>("/api/problems").then(r=>setProblems(r.data)).catch(e=>setError(apiError(e))).finally(()=>setLoading(false));},[]);const topics=useMemo(()=>["ALL",...Array.from(new Set(problems.flatMap(p=>p.topics))).sort()], [problems]);const visible=useMemo(()=>problems.filter(p=>(difficulty==="ALL"||p.difficulty===difficulty)&&(topic==="ALL"||p.topics.includes(topic))&&p.title.toLowerCase().includes(search.toLowerCase())),[problems,difficulty,topic,search]);return <main className="mx-auto min-h-screen max-w-6xl px-6 py-7"><header className="flex items-center justify-between"><Link href="/dashboard" className="text-xl font-bold">Peer<span className="text-cyan-400">Solve</span></Link><div className="flex items-center gap-3"><Link className="btn-secondary" href="/dashboard">Dashboard</Link><Link className="btn-primary" href="/world">Campaign World →</Link></div></header><section className="mt-14"><p className="text-sm font-semibold uppercase tracking-[.2em] text-cyan-400">Practice library</p><h1 className="mt-2 text-4xl font-bold">Problems</h1><input className="mt-8 max-w-xl" placeholder="Search problems..." value={search} onChange={e=>setSearch(e.target.value)}/><Filter label="Difficulty" values={difficulties} current={difficulty} set={setDifficulty}/><Filter label="Topics" values={topics} current={topic} set={setTopic}/>{loading?<p className="mt-10 text-slate-400">Loading problems…</p>:error?<p className="mt-10 text-rose-400">{error}</p>:<div className="mt-8 grid gap-4 md:grid-cols-2">{visible.map(p=><Link key={p.id} href={`/problems/${p.id}`} className="card p-6 transition hover:-translate-y-0.5 hover:border-cyan-400"><div className="flex items-start justify-between gap-4"><h2 className="text-xl font-bold">{p.title}</h2><Badge value={p.difficulty}/></div><p className="mt-4 text-sm text-slate-400">{p.topics.map(t=>format(t)).join(" • ")}</p></Link>)}{visible.length===0&&<p className="text-slate-400">No matching problems.</p>}</div>}</section></main>}
function Filter({label,values,current,set}:{label:string;values:readonly string[];current:string;set:(value:any)=>void}){return <div className="mt-5"><p className="mb-2 text-sm text-slate-400">{label}</p><div className="flex flex-wrap gap-2">{values.map(v=><button key={v} onClick={()=>set(v)} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${current===v?"bg-cyan-400 text-slate-950":"border border-slate-700 text-slate-300"}`}>{format(v)}</button>)}</div></div>}
